# Generated by Django 5.1.4 on 2025-01-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_form_question_submission_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
