# Generated by Django 5.1.5 on 2025-02-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_answer_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_float',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='min_value',
            field=models.FloatField(null=True),
        ),
    ]
