# Generated by Django 5.1.5 on 2025-03-17 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_is_float_alter_question_max_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
