# Generated by Django 5.1.5 on 2025-03-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_form_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('color', 'Color'), ('choice', 'Choice')], max_length=32),
        ),
    ]
