name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: pull changes & restart docker compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          # probably not the best approach, but i don't want gh actions to wait for my frontend to build
          script: |
            nohup bash -c 'cd ~/cuesti && git pull && docker compose up -d --build' > ~/cuesti/deploy.log 2>&1 &
